language: node_js
node_js:
  - "10"

os:
  - linux
  - windows

branches:
  only:
    - testcafelivemodefails

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH="$HOME/.yarn/bin:$PATH"; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install googlechrome; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install firefox; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then REG QUERY HKLM\\SOFTWARE\\Clients\\StartMenuInternet //s //f Chrome; REG QUERY HKLM\\SOFTWARE\\Clients\\StartMenuInternet //s //f Firefox; fi
  - yarn install

env:
  - MOZ_HEADLESS=1

addons:
  chrome: stable
  firefox: latest
  apt:
    packages:
      - imagemagick

script:
  - yarn start &
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then REG QUERY HKLM\\SOFTWARE\\Clients\\StartMenuInternet //s //f Chrome; REG QUERY HKLM\\SOFTWARE\\Clients\\StartMenuInternet //s //f Firefox; fi
  - netstat -an
  - curl -s localhost:8080 >/dev/null && echo Success. || echo Fail.
  - env
    # https://docs.travis-ci.com/user/reference/windows/
    # Git BASH is the shell that’s used to run your build. See Git for Windows for more details.
  - echo $PATH
  - yarn testcafe --list-browsers
  - yarn test
  - kill %1

notifications:
  email:
    recipients:
      - dev-mails@gmx.net
