language: node_js
node_js:
  - "10"

os:
  - linux
  - windows

branches:
  only:
    - testcafelivemodefails

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install googlechrome; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install firefox; fi
  - yarn
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then echo %PATH%; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo $PATH; fi
  - yarn testcafe --list-browsers

env:
  - MOZ_HEADLESS=1

addons:
  chrome: stable
  firefox: latest
  apt:
    packages:
      - imagemagick

script: yarn ci

notifications:
  email:
    recipients:
      - dev-mails@gmx.net
